# Generated by Django 3.1.1 on 2020-10-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain_table',
            new_name='UploadImage',
        ),
    ]
