# Generated by Django 3.1.1 on 2020-10-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='images/icon.png', upload_to='images/')),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
